/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FUNCTIONS_H_RPCGEN
#define _FUNCTIONS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define SERVICE_1 0x20000001
#define PRINTMSG_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define PRINTMSG_1 1
extern  int * printmsg_1_1(char **, CLIENT *);
extern  int * printmsg_1_1_svc(char **, struct svc_req *);
extern int service_1_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PRINTMSG_1 1
extern  int * printmsg_1_1();
extern  int * printmsg_1_1_svc();
extern int service_1_1_freeresult ();
#endif /* K&R C */

#define SERVICE_2 0x20000002
#define PRINTMSG_2 1

#if defined(__STDC__) || defined(__cplusplus)
#define PRINTMSG_2 1
extern  int * printmsg_2_1(char **, CLIENT *);
extern  int * printmsg_2_1_svc(char **, struct svc_req *);
extern int service_2_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PRINTMSG_2 1
extern  int * printmsg_2_1();
extern  int * printmsg_2_1_svc();
extern int service_2_1_freeresult ();
#endif /* K&R C */

#define SERVICE_3 0x20000003
#define PRINTMSG_3 1

#if defined(__STDC__) || defined(__cplusplus)
#define PRINTMSG_3 1
extern  int * printmsg_3_1(char **, CLIENT *);
extern  int * printmsg_3_1_svc(char **, struct svc_req *);
extern int service_3_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PRINTMSG_3 1
extern  int * printmsg_3_1();
extern  int * printmsg_3_1_svc();
extern int service_3_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FUNCTIONS_H_RPCGEN */
